import { Octokit } from "@octokit/rest";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const OWNER = process.env.GITHUB_OWNER ?? "page5888";

export interface DeployResult {
  repoName: string;
  repoUrl: string;
  pagesUrl: string;
}

/**
 * Deploy the given index.html as a new public GitHub repo with Pages enabled.
 * Returns the GitHub Pages URL. Note: Pages first build takes ~30-60s, so
 * the URL may 404 briefly after return.
 */
export async function deployHtmlToPages(
  html: string,
  slug: string,
): Promise<DeployResult> {
  const safeSlug = slug
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "site";
  const repoName = `site-${safeSlug}-${Date.now()}`;

  // 1. Create the repo (auto_init so the default branch exists)
  const { data: repo } = await octokit.repos.createForAuthenticatedUser({
    name: repoName,
    description: `Generated by Web-Cteater for ${slug}`,
    private: false,
    auto_init: true,
  });

  // 2. Upload index.html to the default branch
  await octokit.repos.createOrUpdateFileContents({
    owner: OWNER,
    repo: repoName,
    path: "index.html",
    message: "feat: initial generated site",
    content: Buffer.from(html, "utf-8").toString("base64"),
    branch: repo.default_branch ?? "main",
  });

  // 3. Enable GitHub Pages on main / root
  try {
    await octokit.request("POST /repos/{owner}/{repo}/pages", {
      owner: OWNER,
      repo: repoName,
      source: {
        branch: repo.default_branch ?? "main",
        path: "/",
      },
    });
  } catch (err) {
    // If Pages already exists or account lacks permissions, swallow
    // and let the URL still be returned for manual follow-up.
    console.error("[github] enable Pages failed:", err);
  }

  return {
    repoName,
    repoUrl: repo.html_url,
    pagesUrl: `https://${OWNER}.github.io/${repoName}/`,
  };
}
